### ISSUE TITLE
Make wait() a timed wait and add waitFor() and pass in a truth block.

### ISSUE THREAD

**Issue by dostrander** [Raizlabs/FRY#15]
- So we can allow for truthiness waits. ex: wait until all CAAnimations are out of the layer's animation queue.

**Comment by dostrander** [comment]
@KingOfBrian I'm not authorized allowed to label anything or else I'd label it an enhancement

**Comment by KingOfBrian** [comment]
This should be much clearer in the 1.0 branch.
